NameError
Python 3.7.6: D:\python\BoMaiApp2\venv\Scripts\python.exe
Mon Jan 17 10:54:59 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 D:\python\BoMaiApp2\EldLabelMG\main_eld_app.py in <module>()
    8 
    9 import win32api
   10 from shiboken2.shiboken2 import *
   11 from PySide2.QtCore import QObject, QTranslator, Qt
   12 from PySide2.QtGui import QIcon, QPixmap
shiboken2 undefined

 D:\python\BoMaiApp2\venv\lib\site-packages\shiboken2\__init__.py in <module>()
   27 # from .shiboken2 import *
   28 # from shiboken2.shiboken2 import *
   29 
   30 # Trigger signature initialization via __builtins__.
   31 _init_pyside_extension()
_init_pyside_extension undefined
NameError: name '_init_pyside_extension' is not defined
    __cause__ = None
    __class__ = <class 'NameError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of NameError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of NameError object>
    __doc__ = 'Name not found globally.'
    __eq__ = <method-wrapper '__eq__' of NameError object>
    __format__ = <built-in method __format__ of NameError object>
    __ge__ = <method-wrapper '__ge__' of NameError object>
    __getattribute__ = <method-wrapper '__getattribute__' of NameError object>
    __gt__ = <method-wrapper '__gt__' of NameError object>
    __hash__ = <method-wrapper '__hash__' of NameError object>
    __init__ = <method-wrapper '__init__' of NameError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of NameError object>
    __lt__ = <method-wrapper '__lt__' of NameError object>
    __ne__ = <method-wrapper '__ne__' of NameError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of NameError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of NameError object>
    __repr__ = <method-wrapper '__repr__' of NameError object>
    __setattr__ = <method-wrapper '__setattr__' of NameError object>
    __setstate__ = <built-in method __setstate__ of NameError object>
    __sizeof__ = <built-in method __sizeof__ of NameError object>
    __str__ = <method-wrapper '__str__' of NameError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("name '_init_pyside_extension' is not defined",)
    with_traceback = <built-in method with_traceback of NameError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "D:/python/BoMaiApp2/EldLabelMG/main_eld_app.py", line 10, in <module>
    from shiboken2.shiboken2 import *
  File "D:\python\BoMaiApp2\venv\lib\site-packages\shiboken2\__init__.py", line 31, in <module>
    _init_pyside_extension()
NameError: name '_init_pyside_extension' is not defined

